version: "3.6"

services:
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: intros

  redis:
    image: redis:6.2.5
    ports:
      - "6380:6379"

volumes:
  postgres:
